name = "Ternion"
author = "Betelgeuse27"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc99a1cfd39b9386d79990d974caf01af907ac7df98d288c2b0f4ffb11b01cd5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
