name = "Ternion"
author = "Betelgeuse27"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98ed9b1a994ce638b2d2e03ab89b75cee4750f36a541bc2929c5bfc36f3e0e84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
